# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rpc.matrices_pb2 as matrices__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in matrices_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatrixServiceStub(object):
    """MatrixService Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DistributeMatrix = channel.unary_unary(
                '/matrices.MatrixService/DistributeMatrix',
                request_serializer=matrices__pb2.MatrixRequest.SerializeToString,
                response_deserializer=matrices__pb2.MatrixResponse.FromString,
                _registered_method=True)
        self.SaveResult = channel.unary_unary(
                '/matrices.MatrixService/SaveResult',
                request_serializer=matrices__pb2.ResultRequest.SerializeToString,
                response_deserializer=matrices__pb2.ResultResponse.FromString,
                _registered_method=True)


class MatrixServiceServicer(object):
    """MatrixService Definition
    """

    def DistributeMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DistributeMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeMatrix,
                    request_deserializer=matrices__pb2.MatrixRequest.FromString,
                    response_serializer=matrices__pb2.MatrixResponse.SerializeToString,
            ),
            'SaveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveResult,
                    request_deserializer=matrices__pb2.ResultRequest.FromString,
                    response_serializer=matrices__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matrices.MatrixService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('matrices.MatrixService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatrixService(object):
    """MatrixService Definition
    """

    @staticmethod
    def DistributeMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matrices.MatrixService/DistributeMatrix',
            matrices__pb2.MatrixRequest.SerializeToString,
            matrices__pb2.MatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matrices.MatrixService/SaveResult',
            matrices__pb2.ResultRequest.SerializeToString,
            matrices__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
